server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: tournament-service

  datasource:
    url: jdbc:h2:mem:tournamentdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
