server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: matchmaking-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8081}
